services:
  - type: web
    name: survey-web-app
    env: python
    rootDir: .
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 180 --graceful-timeout 30 --keep-alive 5
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true

